compatibility_date = "2021-11-01"
compatibility_flags = [
  "streams_enable_constructors",
]
main = "dist/server/cloudflare-workers-bundle.js"
name = "ublog"
usage_model = 'bundled'
workers_dev = true

[site]
bucket = "./dist/client"
